### ISSUE TITLE
simple-knn can not be opened.

### ISSUE THREAD

**Issue by USTBVEO** [m-kruse98/SplatPose#3]

**Comment by m-kruse98** [comment]
Hey,

have you made sure to clone the repository recursively to also download the simple-knn and differentiable rasterizer.

The command is
`git clone git@github.com:m-kruse98/SplatPose.git --recursive`

The submodules should then be in the submodule folder. 

All the best
Mathis

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Vien Yann/杨威
 
   This is an automatic reply, confirming that your e-mail was received. Thank you!
