### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by heidapao2b** [m-kruse98/SplatPose#4]
Hello! Thanks for your good job! If I only do 3d defect detection training, what is the approximate gpu usage required.

**Comment by m-kruse98** [comment]
Hey, sorry for the late reply,

this depends on the scene. For the simple scenes in the MAD dataset, only a few GB (2-3) of VRAM were needed. The paper tests were done with RTX 3090 GPUs, but I also did successful tests with 1080 Ti GPUs.

For larger scenes, it may be a bit more. But usually one decently sized GPU is more than enough.

All the best,
Mathis

**Comment by heidapao2b** [comment]
OK!Thank you for your reply.
&nbsp;


方同学
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月14日(星期四) 晚上6:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [m-kruse98/SplatPose] GPU Usage (Issue #4)














 
Hey, sorry for the late reply,
 
this depends on the scene. For the simple scenes in the MAD dataset, only a few GB (2-3) of VRAM were needed. The paper tests were done with RTX 3090 GPUs, but I also did successful tests with 1080 Ti GPUs.
 
For larger scenes, it may be a bit more. But usually one decently sized GPU is more than enough.
 
All the best,
 Mathis
